image: java:8

stages:
  - build
  - deploy

build:
  stage: build
  script: ./mvnw clean install

  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  script: scp -i cfranking@165.22.111.98:application/  target/cfranking-0.0.1-SNAPSHOT.jar

  only:
    - master